//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrder()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime DateOrdered { get; set; }
		public string ProductDesc { get; set; }
		public int QTY { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<OrderLine> OrderLines { get; set; }

        public virtual OrderLine Product { get; set; }
		public virtual OrderLine OrderLine { get; set; }
	}
}
